export const data = [
  {
    name: "Moeed Tahir",
    email: "info@makelastingchange.com",
    company: "Abc Company",
    date: "09 May 2022",
    score: "08",
    bid: "$100",
    status: "Pending",
  },
  {
    name: "Jamal Kerrod",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "09 May 2022",
    score: "08",
    bid: "$100",
    status: "Pending",
  },
  {
    name: "Shamus Tuttle",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "19 Nov 2022",
    score: "07",
    bid: "$150",
    status: "Reject",
  },
  {
    name: "Devonne Wallbridge",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "25 Sep 2022",
    score: "09",
    bid: "$200",
    status: "Reject",
  },
  {
    name: "Ariella Filippyev",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "15 Dec 2022",
    score: "04",
    bid: "$250",
    status: "Accept",
  },
  {
    name: "Yelena O'Hear",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "09 Jun 2022",
    score: "06",
    bid: "$350",
    status: "Accept",
  },
  {
    name: "Shamus Tuttle",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "19 Nov 2022",
    score: "07",
    bid: "$150",
    status: "Reject",
  },
  {
    name: "Devonne Wallbridge",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "25 Sep 2022",
    score: "09",
    bid: "$200",
    status: "Reject",
  },
  {
    name: "Ariella Filippyev",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "15 Dec 2022",
    score: "04",
    bid: "$250",
    status: "Accept",
  },
  {
    name: "Yelena O'Hear",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "09 Jun 2022",
    score: "06",
    bid: "$350",
    status: "Accept",
  },
  {
    name: "Shamus Tuttle",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "19 Nov 2022",
    score: "07",
    bid: "$150",
    status: "Reject",
  },
  {
    name: "Devonne Wallbridge",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "25 Sep 2022",
    score: "09",
    bid: "$200",
    status: "Reject",
  },
  {
    name: "Ariella Filippyev",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "15 Dec 2022",
    score: "04",
    bid: "$250",
    status: "Accept",
  },
  {
    name: "Yelena O'Hear",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "09 Jun 2022",
    score: "06",
    bid: "$350",
    status: "Accept",
  },
  {
    name: "Shamus Tuttle",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "19 Nov 2022",
    score: "07",
    bid: "$150",
    status: "Reject",
  },
  {
    name: "Devonne Wallbridge",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "25 Sep 2022",
    score: "09",
    bid: "$200",
    status: "Reject",
  },
  {
    name: "Ariella Filippyev",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "15 Dec 2022",
    score: "04",
    bid: "$250",
    status: "Accept",
  },
  {
    name: "Yelena O'Hear",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "09 Jun 2022",
    score: "06",
    bid: "$350",
    status: "Accept",
  },
  {
    name: "Shamus Tuttle",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "19 Nov 2022",
    score: "07",
    bid: "$150",
    status: "Reject",
  },
  {
    name: "Devonne Wallbridge",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "25 Sep 2022",
    score: "09",
    bid: "$200",
    status: "Reject",
  },
  {
    name: "Ariella Filippyev",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "15 Dec 2022",
    score: "04",
    bid: "$250",
    status: "Accept",
  },
  {
    name: "Yelena O'Hear",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "09 Jun 2022",
    score: "06",
    bid: "$350",
    status: "Accept",
  },
  {
    name: "Shamus Tuttle",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "19 Nov 2022",
    score: "07",
    bid: "$150",
    status: "Reject",
  },
  {
    name: "Devonne Wallbridge",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "25 Sep 2022",
    score: "09",
    bid: "$200",
    status: "Reject",
  },
  {
    name: "Ariella Filippyev",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "15 Dec 2022",
    score: "04",
    bid: "$250",
    status: "Accept",
  },
  {
    name: "Yelena O'Hear",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "09 Jun 2022",
    score: "06",
    bid: "$350",
    status: "Accept",
  },
  {
    name: "Shamus Tuttle",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "19 Nov 2022",
    score: "07",
    bid: "$150",
    status: "Reject",
  },
  {
    name: "Devonne Wallbridge",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "25 Sep 2022",
    score: "09",
    bid: "$200",
    status: "Reject",
  },
  {
    name: "Ariella Filippyev",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "15 Dec 2022",
    score: "04",
    bid: "$250",
    status: "Accept",
  },
  {
    name: "Yelena O'Hear",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "09 Jun 2022",
    score: "06",
    bid: "$350",
    status: "Accept",
  },
  {
    name: "Lutero Aloshechkin",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "01 Aug 2022",
    score: "09",
    bid: "$300",
    status: "Accept",
  },
  {
    name: "Raynell Clendenenn",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "22 Oct 2022",
    score: "07",
    bid: "$80",
    status: "Accept",
  },
  {
    name: "Raynell Clendenenn",
    email: "abcdef@gmail.com",
    company: "Abc Company",
    date: "22 Oct 2022",
    score: "07",
    bid: "$80",
    status: "Accept",
  },
];